[GLOBAL]
pants_version = "2.27.0"

backend_packages = [
  "pants.backend.docker",
  "pants.backend.python",
  "pants.backend.experimental.python.lint.ruff.format",
  "pants.backend.experimental.python.lint.ruff.check",
]

[source]
root_patterns = ["/"]

[python]
interpreter_constraints = ['>=3.12']
enable_resolves = true
default_resolve = "env-default"

[python-bootstrap]
search_path = ["<PYENV_LOCAL>", "/usr/bin"]

[python.resolves]
env-default = "lockfiles/default.lock"
env-data-processor = "lockfiles/service_data_processor.lock"
env-pytest = "lockfiles/tools_pytest.lock"
env-ruff = "lockfiles/tools_ruff.lock"
