[GLOBAL]
pants_version = "2.27.0"

backend_packages = [
  "pants.backend.docker",
  "pants.backend.python",
  "pants.backend.experimental.python.lint.ruff.format",
  "pants.backend.experimental.python.lint.ruff.check",
  
]

[python]
interpreter_constraints = ['>=3.12']

[python-bootstrap]
search_path = ["<PYENV_LOCAL>", "/usr/bin"]
