[GLOBAL]
pants_version = "2.27.0"

backend_packages = [
  "pants.backend.docker",
  "pants.backend.python",
  "pants.backend.build_files.fmt.ruff",
  "pants.backend.experimental.python.lint.ruff.format",
  "pants.backend.experimental.python.lint.ruff.check",
  "pants.backend.shell",
  "pants.backend.shell.lint.shellcheck",
  "pants.backend.shell.lint.shfmt",
]

[source]
root_patterns = ["/"]

[python]
interpreter_constraints = ["CPython>=3.10"]
enable_resolves = true
default_resolve = "env-default"

[python-bootstrap]
search_path = ["<PYENV_LOCAL>", "/usr/bin"]

[python.resolves]
env-default = "lockfiles/default.lock"
env-data-processor = "lockfiles/service_data_processor.lock"
env-pytest = "lockfiles/tools_pytest.lock"
env-ruff = "lockfiles/tools_ruff.lock"

[shfmt]
args = ["-i 4", "-ci", "-sr"]
