shell_sources(
    sources=["*.sh"],
)

file(
    name="pex-python311-aarch64",
    source="pex-python311-aarch64.json",
)

file(
    name="pex-python311-amd64",
    source="pex-python311-amd64.json",
)
